#!/bin/bash
#BSUB -J cleanup_master
#BSUB -W 168:00        # 168 hours = 7 days
#BSUB -n 1
#BSUB -R "rusage[mem=4GB]"   # adjust if needed
#BSUB -o cleanup_master.out
#BSUB -e cleanup_master.err
#BSUB -q long


echo "Starting shapedb nn search controller job at $(date)"


#the ligand being used as a target for shapedb
ligand=/pi/summer.thyme-umw/rosetta_discovery_space/pth2/thymelab_pth2_discovery/pth2_structures/peptide_shapes/upper/upper_res29_34_shifted.mol2
#the working location (if not wanting to run where this script is being called)
working_location=/pi/summer.thyme-umw/rosetta_discovery_space/pth2/testing


python /pi/summer.thyme-umw/enamine-REAL-2.6billion/umass_chan_REAL-M_platform/shapedb/nnsearch_controller.py $ligand $working_location

echo "All chunks processed. Finished at $(date)"